project 'PKDex.xcodeproj/'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'PKDex' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Networking
  pod 'Moya'

  target 'PKDexTests' do
    inherit! :search_paths
    pod 'Moya'
    pod 'Quick'
    pod 'Nimble'
    pod 'Nimble-Snapshots'
  end

  target 'PKDexUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Moya'
    pod 'Quick'
    pod 'Nimble'
    pod 'Nimble-Snapshots'
  end

end
